# Generated by Django 2.2.4 on 2020-05-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsersApp', '0001_initial'),
        ('TruckApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviews',
            new_name='Review',
        ),
    ]
