# Generated by Django 2.2.4 on 2020-05-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200522_0951'),
        ('misc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='posted_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='user_app.User'),
            preserve_default=False,
        ),
    ]
