# Generated by Django 2.2.4 on 2020-05-27 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20200527_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lobbies',
        ),
    ]
