# Generated by Django 2.2.4 on 2020-05-19 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0002_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message_of_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_message', to='the_wall_app.Messages')),
                ('user_of_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_user', to='the_wall_app.Users')),
            ],
        ),
    ]
