# Generated by Django 2.2.4 on 2020-05-13 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninjas',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
