# Generated by Django 2.2.4 on 2020-05-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
        ('MatchmakingApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='users',
        ),
        migrations.AddField(
            model_name='lobby',
            name='users',
            field=models.ManyToManyField(related_name='lobbies', to='LoginApp.User'),
        ),
    ]
