# Generated by Django 2.2.4 on 2020-05-29 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LoginApp', '0001_initial'),
        ('MatchmakingApp', '0003_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friendslist', to='LoginApp.User'),
            preserve_default=False,
        ),
    ]
