# Generated by Django 2.2.4 on 2020-05-29 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchmakingApp', '0004_friend_created_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
