# Generated by Django 2.2.4 on 2020-05-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shows',
            name='description',
            field=models.CharField(default='sample description here', max_length=255),
            preserve_default=False,
        ),
    ]
